### ISSUE TITLE
Strange /metrics behaviour when resolving alert via dashboard

### ISSUE THREAD

**Issue by nbzero** [StartloJ/graylog-alert-exporter#11]
If you use dashboard to resolve the alert while there are other alerts present, the metrics page seems to get reset and show only some alerts that are resolved.

**Reproduce steps**
1. Generate multiple alerts and monitor /metrics page.
![image](https://user-images.githubusercontent.com/11268946/124533166-08aea780-de3c-11eb-8a90-aafc1f11a820.png)
![image](https://user-images.githubusercontent.com/11268946/124533178-0d735b80-de3c-11eb-8bcb-acf649f9e570.png)

2. Go to dashboard and resolved some of the alerts.
![image](https://user-images.githubusercontent.com/11268946/124533317-4e6b7000-de3c-11eb-84d8-ed261ad96dfe.png)

3. Check metrics page again and you'll see that an alert that is firing isn't showing.
![image](https://user-images.githubusercontent.com/11268946/124533290-41e71780-de3c-11eb-9bef-45b41dbdb14f.png)

4. If 'Sample Data Aggregation' is firing again the metrics will show only the resolved one.
![image](https://user-images.githubusercontent.com/11268946/124533684-fc771a00-de3c-11eb-9d00-9c9a0b916785.png)
![image](https://user-images.githubusercontent.com/11268946/124533668-f6813900-de3c-11eb-83bb-fa7d13d466ff.png)

5. If I delete the resolved alert metrics will show firing alerts again.
![image](https://user-images.githubusercontent.com/11268946/124533860-4d870e00-de3d-11eb-8229-951de66d0105.png)
![image](https://user-images.githubusercontent.com/11268946/124533839-45c76980-de3d-11eb-948a-280f6988c37e.png)

Not really sure why this happens, maybe metrics have a bug where it couldn't show both 0 and 1 value?

**Comment by PePoDev** [comment]
Thanks for reporting us.

I have seen the problem, And will solve this soon.

**Comment by PePoDev** [comment]
@nbzero Can you check this branch and confirm this is solved?
