### ISSUE TITLE
Dashboard doesn't work in offline environment

### ISSUE THREAD

**Issue by nbzero** [StartloJ/graylog-alert-exporter#7]
![image](https://user-images.githubusercontent.com/11268946/122538437-bbb38e80-d050-11eb-90f9-38409d359fef.png)

From screenshot above you can see that dashboard page doesn't render properly.
This should be because CSS and script are being loaded from online source, because the machine accessing dashboard is in offline environment without internet access.

To fix this I think you can specify Tailwind and Vue to a certain version and serve those assets from inside.

**Comment by PePoDev** [comment]
I have fixed it in this commit https://github.com/StartloJ/graylog-alert-exporter/pull/6/commits/b0d63724e0e13db78821a9f3de7ab2f8d213616d

Try local build and confirm if this works, Thanks.
