### ISSUE TITLE
Found little mistake insert API feature

### ISSUE THREAD

**Issue by StartloJ** [StartloJ/graylog-alert-exporter#8]
I found bug on insert data into database with API in this reproduce action:
1. Run app in go-cli or build binary with `go run main.go` or `make build && ./graylog-alert-exporter`
2. Send API data with some fake **JSON** in **POST** method like:
```json
{
    "statuscode":"500",
    "kubernetes_namespace_name":"router",
    "kubernetes_pod_name":"nginx-tester",
    "some_info":"foo",
    "zone":"OPSTA"
}
```
From step 2, you will see the return message:
```json
{
    "data": {
        "message": "resource updated successfully"
    },
    "status": "success"
}
```
!!! But, I found seem error log in application and data can't update in database:
```console
ERRO[06/20/2021 12:37:18 AM] Error to insert record into database: object missing primary index
```
I think it should return to client with a `fail message` or `error code`.

**Comment by PePoDev** [comment]
The design is Graylog must always fire alert in JSON format with required field `event_definition_title` And Exporter will use this field as primary key in a local database.

I will add an error handler for the `InsertAlert` function to return HTTP status fail when it can't add data to database.

**Comment by PePoDev** [comment]
```rest
POST http://localhost:9889/metrics HTTP/1.1
content-type: application/json

{
    "statuscode":"500",
    "kubernetes_namespace_name":"router",
    "kubernetes_pod_name":"nginx-tester",
    "some_info":"foo",
    "zone":"OPSTA"
}
```

I can't reproduce it.

I have test with the above JSON and it's working without any error because the primary key is hashed value from `event_definition_title` they will not empty at all.

Can you explain how do you create a request and provide a full debug log?

**Comment by StartloJ** [comment]
OK. sorry about step when I add new metrics in:
```bash
$ curl --request POST 'http://127.0.0.1:9889/api/alert' \
--header 'Content-Type: application/json' \
--data '{
    "statuscode":"500",
    "kubernetes_namespace_name":"router",
    "kubernetes_pod_name":"nginx-tester",
    "some_info":"foo",
    "zone":"OPSTA"
}'

you can see error log in app console.
```

**Comment by PePoDev** [comment]
The correct URL should be `http://localhost:9889/metrics`, This endpoint use to receive a Graylog alert.

And `http://localhost:9889/api/*` just use to communicate between UI and Exporter, You shouldn't use it directly.
